apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solidarityhub

resources:
  - ../../base

images:
  - name: api-gateway
    newName: sh/api-gateway
    newTag: local

  - name: identity-api
    newName: sh/identity-api
    newTag: local

  - name: campaign-api
    newName: sh/campaign-api
    newTag: local

  - name: donation-processor
    newName: sh/donation-processor
    newTag: local
