apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solidarityhub

resources:
  - namespace.yaml
  - config/app-configmap.yaml
  - secrets/app-secrets.yaml

  - infra/postgres-init-configmap.yaml
  - infra/postgres.yaml
  - infra/rabbitmq.yaml

  - apps/identity-api.yaml
  - apps/campaign-api.yaml
  - apps/donation-processor.yaml
  - apps/api-gateway.yaml

  - observability/loki.yaml
  - observability/jaeger.yaml
  - observability/prometheus.yaml
  - observability/grafana.yaml
  - observability/zabbix.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - observability/files/prometheus.yml

  - name: grafana-datasources
    files:
      - observability/files/datasources.yml

  - name: grafana-dashboard-providers
    files:
      - observability/files/dashboard.yml

  - name: grafana-dashboards
    files:
      - observability/files/solidarityhub-overview.json

  - name: grafana-dashboards-zabbix
    files:
      - observability/files/solidarityhub-infra-zabbix.json

generatorOptions:
  disableNameSuffixHash: true
