apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway

spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: identity-api

spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: campaign-api

spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: donation-processor

spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
