apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solidarityhub

resources:
  - ../../base
  - ghcr-secret.yaml

images:
  - name: api-gateway
    newName: ghcr.io/alessandromaia/solidarityhub/api-gateway
    newTag: 1.0.0
  - name: identity-api
    newName: ghcr.io/alessandromaia/solidarityhub/identity-api
    newTag: 1.0.0
  - name: campaign-api
    newName: ghcr.io/alessandromaia/solidarityhub/campaign-api
    newTag: 1.0.0
  - name: donation-processor
    newName: ghcr.io/alessandromaia/solidarityhub/donation-processor
    newTag: 1.0.0

patches:
  - path: app-config-patch.yaml
  - path: image-pull-secret-patch.yaml
