// <auto-generated />
using System;
using Campaign.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Campaign.Infrastructure.Migrations
{
    [DbContext(typeof(CampaignContext))]
    [Migration("20260322183207_FixCampaignTotalValueObjectMapping")]
    partial class FixCampaignTotalValueObjectMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("campaign_db")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.CampaignAggregate.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("campaigns", "campaign_db");
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.CampaignAggregate.Entities.CampaignStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("new_status");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("old_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("campaign_status_history", "campaign_db");
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.CampaignAggregate.Entities.DonationLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<int>("DonationIntentId")
                        .HasColumnType("integer")
                        .HasColumnName("donation_intent_id");

                    b.Property<int>("DonorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("donor_user_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("donation_ledger_entries", "campaign_db");
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.DonationIntentAggregate.Entities.DonationIntent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<int>("DonorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("donor_user_id");

                    b.Property<string>("MessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("donation_intents", "campaign_db");
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.DonationIntentAggregate.Entities.DonationIntentDeadLetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<int>("DonationIntentId")
                        .HasColumnType("integer")
                        .HasColumnName("donation_intent_id");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("MessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_id");

                    b.HasKey("Id");

                    b.HasIndex("DonationIntentId");

                    b.ToTable("donation_intent_dead_letters", "campaign_db");
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.DonationIntentAggregate.Entities.DonationIntentProcessingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DonationIntentId")
                        .HasColumnType("integer")
                        .HasColumnName("donation_intent_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_name");

                    b.HasKey("Id");

                    b.HasIndex("DonationIntentId");

                    b.ToTable("donation_intent_processing_logs", "campaign_db");
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.CampaignAggregate.Entities.Campaign", b =>
                {
                    b.OwnsOne("Campaign.Domain.AggregatesModel.CampaignAggregate.ValueObjects.CampaignPeriod", "Period", b1 =>
                        {
                            b1.Property<int>("CampaignId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_date");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_date");

                            b1.HasKey("CampaignId");

                            b1.ToTable("campaigns", "campaign_db");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.OwnsOne("Campaign.Domain.AggregatesModel.CampaignAggregate.ValueObjects.CampaignTotal", "Total", b1 =>
                        {
                            b1.Property<int>("CampaignId")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("LastDonationAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_donation_at");

                            b1.Property<decimal>("TotalAmountRaised")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount_raised");

                            b1.Property<int>("TotalDonationsCount")
                                .HasColumnType("integer")
                                .HasColumnName("total_donations_count");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("total_updated_at");

                            b1.HasKey("CampaignId");

                            b1.ToTable("campaigns", "campaign_db");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.OwnsOne("Campaign.Domain.AggregatesModel.CampaignAggregate.ValueObjects.Money", "FinancialGoal", b1 =>
                        {
                            b1.Property<int>("CampaignId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("financial_goal_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("financial_goal_currency");

                            b1.HasKey("CampaignId");

                            b1.ToTable("campaigns", "campaign_db");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");
                        });

                    b.Navigation("FinancialGoal")
                        .IsRequired();

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.CampaignAggregate.Entities.CampaignStatusHistory", b =>
                {
                    b.HasOne("Campaign.Domain.AggregatesModel.CampaignAggregate.Entities.Campaign", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.CampaignAggregate.Entities.DonationLedgerEntry", b =>
                {
                    b.HasOne("Campaign.Domain.AggregatesModel.CampaignAggregate.Entities.Campaign", null)
                        .WithMany("DonationLedger")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.DonationIntentAggregate.Entities.DonationIntentDeadLetter", b =>
                {
                    b.HasOne("Campaign.Domain.AggregatesModel.DonationIntentAggregate.Entities.DonationIntent", null)
                        .WithMany("DeadLetters")
                        .HasForeignKey("DonationIntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.DonationIntentAggregate.Entities.DonationIntentProcessingLog", b =>
                {
                    b.HasOne("Campaign.Domain.AggregatesModel.DonationIntentAggregate.Entities.DonationIntent", null)
                        .WithMany("ProcessingLogs")
                        .HasForeignKey("DonationIntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.CampaignAggregate.Entities.Campaign", b =>
                {
                    b.Navigation("DonationLedger");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Campaign.Domain.AggregatesModel.DonationIntentAggregate.Entities.DonationIntent", b =>
                {
                    b.Navigation("DeadLetters");

                    b.Navigation("ProcessingLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
