apiVersion: v1
kind: Secret

metadata:
  name: app-secrets

type: Opaque

stringData:
  POSTGRES_ADMIN_USER: "dbadmin"
  POSTGRES_ADMIN_PASSWORD: "change-me-postgres-admin-password"

  IDENTITY_DB_NAME: "identity_db"
  IDENTITY_DB_USER: "identity_user"
  IDENTITY_DB_PASSWORD: "change-me-identity-db-password"

  CAMPAIGN_DB_NAME: "campaign_db"
  CAMPAIGN_DB_USER: "campaign_user"
  CAMPAIGN_DB_PASSWORD: "change-me-campaign-db-password"

  RABBITMQ_USER: "solidarity_user"
  RABBITMQ_PASSWORD: "change-me-rabbitmq-password"

  JwtSettings__Secret: "change-me-local-dev-jwt-secret-with-at-least-32-chars"
  AdminSeed__Password: "Admin@2026!"
  GRAFANA_ADMIN_PASSWORD: "change-me-grafana-password"

  ConnectionStrings__IdentityDb: "Host=postgres;Port=5432;Database=identity_db;Username=identity_user;Password=change-me-identity-db-password"
  ConnectionStrings__CampaignDb: "Host=postgres;Port=5432;Database=campaign_db;Username=campaign_user;Password=change-me-campaign-db-password"
  ConnectionStrings__RabbitMQ: "amqp://solidarity_user:change-me-rabbitmq-password@rabbitmq:5672"

  ZABBIX_DB_PASSWORD: "change-me-zabbix-db-password"
