apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config

data:
  ASPNETCORE_ENVIRONMENT: "Development"
  DOTNET_ENVIRONMENT: "Development"

  JwtSettings__Issuer: "SH.IdentityService"
  JwtSettings__Audience: "SH.Client"
  JwtSettings__AccessTokenExpirationMinutes: "60"
  JwtSettings__RefreshTokenExpirationDays: "7"

  AdminSeed__Enabled: "false"
  AdminSeed__FirstName: "Administrador"
  AdminSeed__LastName: "ONG"
  AdminSeed__Email: "admin@conexaosolidaria.local"
  AdminSeed__Cpf: "52998224725"

  DonationOptions__Succeded: "true"
  Prometheus__UriPrefixes__0: "http://+:9464/"

  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  ConnectionStrings__Loki: "http://loki:3100"
